name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  install_docker:
    runs-on: self-hosted  # Utilizamos el runner auto-hospedado (tu EC2)

    steps:
      # Paso 1: Instalar Docker (si no está instalado) en Amazon Linux 2023
      - name: Install Docker on EC2 (Amazon Linux 2023)
        run: |
          # Actualizar el sistema
          sudo yum update -y
          
          # Instalar Docker
          sudo dnf install -y docker

          # Iniciar y habilitar Docker
          sudo systemctl start docker
          sudo systemctl enable docker

  deploy:
    runs-on: self-hosted  # Asegúrate de que este job también esté en el EC2

    needs: install_docker  # Este job depende de que el job de instalación termine exitosamente

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Construir y empujar la imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: millanda29/reydefrancia_nextsj:latest
        run: |
          sudo docker buildx build --file ./Dockerfile --iidfile /home/ec2-user/actions-runner/_work/_temp/docker-actions-toolkit-duhgNF/build-iidfile-b2bac07214.txt --tag millanda29/reydefrancia_nextsj:latest --push .

      # Paso 4: Detener y eliminar cualquier contenedor anterior
      - name: Stop and remove previous container
        run: |
          docker stop reydefrancia || true
          docker rm reydefrancia || true

      # Paso 5: Ejecutar el contenedor
      - name: Run Docker container
        run: |
          docker run -d --name reydefrancia -p 80:3000 millanda29/reydefrancia_nextsj:latest
